import { test, expect } from "./fixture"

test("s12-08 live text entry guards global hotkeys with escape as the only exception", async ({ agentic, page }) => {
  await agentic.promptForScript("edit-file")
  await agentic.waitForIdle()
  const status = page.getByTestId("terminal-status")
  const prompt = page.locator("#promptbox")
  const initialStatus = await status.innerText()
  await prompt.focus()
  await page.keyboard.type("alpha beta")
  await expect(prompt).toHaveValue("alpha beta")
  await expect(status).toHaveText(initialStatus)
  const label = page.getByTestId("terminal-step-label")
  await page.keyboard.press("v")
  await expect(agentic.root).toHaveAttribute("data-view", "mission")
  const beforePromptArrow = await label.innerText()
  const beforePromptLast = beforePromptArrow.split("/")[1]
  await page.keyboard.press("ArrowLeft")
  await expect(label).toHaveText(new RegExp(`^${beforePromptLast}/${beforePromptLast}$`))

  await page.getByTestId("terminal-diff-header").filter({ hasText: "fixture.ts" }).click()
  const viewer = page.locator('[data-screen-label="File viewer"]')
  await viewer.locator('[data-viewer-action="edit"]').click()
  const editor = page.locator("#fileeditor")
  const original = await editor.inputValue()
  await editor.fill("")
  await editor.focus()
  await page.keyboard.type("one two")
  await expect(editor).toHaveValue("one two")
  const beforeEditorHotkeys = await label.innerText()
  const beforeEditorLast = beforeEditorHotkeys.split("/")[1]
  await page.keyboard.press("v")
  await expect(agentic.root).toHaveAttribute("data-view", "mission")
  await page.keyboard.press("ArrowLeft")
  await expect(label).toHaveText(new RegExp(`^${beforeEditorLast}/${beforeEditorLast}$`))
  await editor.fill(original)
  await editor.press("Escape")
  await expect(viewer).toHaveCount(0)
  await page.keyboard.press("v")
  await expect(agentic.root).toHaveAttribute("data-view", "tui")
})
